# 00_libraries.R

suppressPackageStartupMessages({
  library(dplyr)
  library(tibble)
  library(ggplot2)
  library(purrr)
  library(tidyr)
  library(forcats)
  library(furrr)
  library(future)
  library(igraph)
  library(extraDistr)
  # library(vegan)
  library(backbone)
  library(Matrix)
  library(patchwork)
  library(scales)
  library(ggsci)
  # library(ggtext)
  library(latex2exp)
  library(mgcv)
  library(broom)
  library(here)
})
